### ISSUE TITLE
Cp: {sketch_path}: Permission denied - macOS Mojave

### ISSUE THREAD

**Issue by Oortone** [arduino/arduino-cli#2452] opened 2023-12-07 09:10 UTC
System: macOS 10.14.6 (Intel)

Start IDE 2.2.1
Create simple Hello World code
Save  in `Documents/Arduino` (or any other path probably)
Sketch>Export Compiled Binary

error in IDE:
```
cp: {sketch_path}: Permission denied
exit status 1

Compilation error: exit status 1
```

Possibly related:
If I double click any *.ino file when IDE 2.2.1 is not running, IDE starts but the actual sketch is never opened and the Open option under File in the IDE 2.2.1 Menu bar is not even present, there's only a greyed out Close. 

Backing to IDE 2.0.4 eliminates this error.

**Comment by per1234** [comment] 2023-12-07 09:31
Closing as duplicate of https://github.com/arduino/arduino-cli/issues/2340

@Oortone I guess you didn't check your forum topic before you submitted this issue. I already provided a detailed explanation of the problem and instructions for an alternative workaround there:

https://forum.arduino.cc/t/cp-sketch-path-permission-denied/1197659

If you have any questions or concerns, please feel free to reply on the forum topic. I'll be happy to provide assistance over there.

> If I double click any *.ino file when IDE 2.2.1 is not running, IDE starts but the actual sketch is never opened and the Open option under File in the IDE 2.2.1

This is an unrelated bug. It is tracked at https://github.com/arduino/arduino-ide/issues/2209. A fix has already been prepared: https://github.com/arduino/arduino-ide/pull/2288

**Closed by per1234** 2023-12-07 09:31 UTC
Labels: topic: code, type: imperfection, topic: build-process
