### ISSUE TITLE
Add documentation: how to add 3rd party core urls

### ISSUE THREAD

**Issue by embhobbb** [arduino/arduino-cli#42] opened 2018-09-15 10:59 UTC
Hi,
i have installed CLI interface and able to install the core package for AVR. But i am using ESP8266 core. 
I searched for the core but didn't find. 
[code]./arduino-cli-0.2.1-alpha.preview-linuxarm core search esp8266
Searching for platforms matching 'esp8266'

No platforms matching your search[\code]

**Comment by embhobbb** [comment] 2018-09-22 18:33
thanks.
i got error while downloading package for esp8266.

```
./arduino-cli core install esp8266:esp8266
Downloading esp8266:esptool@0.4.13...
esp8266:esptool@0.4.13 downloaded
Error: server returned a non-2XX status code
Error downloading esp8266:esptool@0.4.13

```

**Comment by ljcucc** [comment] 2018-09-24 07:04
Same problem in https://github.com/arduino/arduino-cli/issues/43

**Comment by cmaglie** [comment] 2018-09-24 09:15
Duplicate of #43

**Comment by brusherru** [comment] 2018-09-25 17:03
@cmaglie @ljcucc , it's not the same problem in the topic. 
The topic is about adding some instruction about `additional_urls` into `README.md`.

But then author said about another problem, that is reported in #43. ;)
So I propose to reopen this issue and then just add some documentation.

**Comment by sashad** [comment] 2018-11-27 10:19
ls ./.arduino15/
package_esp8266com_index.json  package_index.json
but
arduino-cli core install esp8266:esp8266
Error: package esp8266 not found
Could not determine platform dependencies

**Comment by zoobab** [comment] 2019-01-25 22:32
@brusherru it is not clear where this file ".cli-config.yml" needs to be located. In ~/.cli-config.yml ? In the current directory? I have added it in ~/.cli-config.yml , but it does not find the esp8266 repo, so I guess it is the wrong location...

**Comment by zoobab** [comment] 2019-01-25 22:38
After some debugging, where I copied the arduino-cli binary in /usr/local/bin/, it looks for the ".cli-config.yml" in this directory, so I copied it there, and now it works, weird: 

```
$ arduino-cli core update-index --debug
INFO[0000] Initiating configuration
INFO[0000] Unserializing configurations from /usr/local/bin/.cli-config.yml
WARN[0000] Error reading config, using default configuration  error="open /usr/local/bin/.cli-config.yml: no such file or directory"
WARN[0000] Did not manage to get config file, using default configuration  error="open /usr/local/bin/.cli-config.yml: no such file or directory"
```

**Comment by per1234** [comment] 2019-05-24 08:44
Closing as fixed by https://github.com/arduino/arduino-cli/commit/3dcd1ca4ae071acb9fa00b93bb4e920606ce63cd

**Closed by per1234** 2019-05-24 08:44 UTC
Labels: documentation

**Comment by adi-g15** [comment] 2022-11-30 04:50
> After some debugging, where I copied the arduino-cli binary in /usr/local/bin/, it looks for the ".cli-config.yml" in this directory, so I copied it there, and now it works, weird:
> 
> ```
> $ arduino-cli core update-index --debug
> INFO[0000] Initiating configuration
> INFO[0000] Unserializing configurations from /usr/local/bin/.cli-config.yml
> WARN[0000] Error reading config, using default configuration  error="open /usr/local/bin/.cli-config.yml: no such file or directory"
> WARN[0000] Did not manage to get config file, using default configuration  error="open /usr/local/bin/.cli-config.yml: no such file or directory"
> ```

To add to this, if you don't want to put a config file in root (like if you are on NixOS), you can use the `--config-file` flag to specify the path to `.cli-config.yml`.
