### ISSUE TITLE
Network configuration items can't be unset

### ISSUE THREAD

**Issue by butor32** [arduino/arduino-cli#1677] opened 2021-11-18 07:29 UTC
### Describe the problem

If you set the `network.proxy` key (e.g., via the "**Network**" tab of the Arduino IDE preferences dialog), then during a later IDE session try to disable the proxy preference, Arduino CLI continues to attempt to connect to the Internet via a proxy.

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Select the "**Network**" tab from the "**Preferences**" dialog.
1. Select the radio button next to "**Manual proxy configuration**".
1. Click the "**OK**" button.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start Arduino IDE.
1. Select **File > Preferences...** from the Arduino IDE menus.
1. Select the "**Network**" tab from the "**Preferences**" dialog.
1. Select the radio button next to "**No proxy**".
1. Click the "**OK**" button.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start Arduino IDE.
1. Select **File > Preferences...** from the Arduino IDE menus.
1. Select the "**Network**" tab from the "**Preferences**" dialog.

🐛 The "**Manual proxy configuration**" radio button is selected.
🐛 When Arduino CLI attempts to download resources from the Internet, an error like "`proxyconnect tcp: dial tcp: lookup _: no such host`" occurs.

### Expected behavior

It is possible to disable the proxy after enabling it.

### Arduino CLI version

0.29.0

### Operating system

- Linux
- Windows

### Operating system version

- Windows 11
- Debian Bullseye

### Additional context

The `network.proxy` key in `~/.arduinoIDE/arduino-cli.yaml` is set to `http://_/`

<a name="workaround"></a>

#### Workaround

1. Select **File > Quit** from the Arduino IDE menus if it is running.
1. Use any text editor to open the file at the following path:
   - **Windows:**
     ```text
     C:\Users\<username>\.arduinoIDE\arduino-cli.yaml
     ```
     (where `<username>` is your Windows username)
   - **Linux:**
     ```text
     ~/.arduinoIDE/arduino-cli.yaml
     ```
     ❗ The `~/.arduinoIDE/` folder may be hidden by default in your file manager and terminal.
   - **macOS:**
     ```text
     ~/.arduinoIDE/arduino-cli.yaml
     ```
     ❗ The `~/.arduinoIDE/` folder is hidden by default. You can make it visible by pressing the <kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**.**</kbd> keyboard shortcut.
1. Delete the lines from the file that have this format:
   ```yaml
   network:
     proxy: <some proxy URL>
     user_agent_ext: daemon
   ```
1. Save the file.
1. Start the Arduino IDE.

You should now find that "**No proxy**" is selected in the "**Network**" tab of the "**Preferences**" dialog.

#### Additional reports

- https://github.com/arduino/arduino-ide/issues/1363
- https://forum.arduino.cc/t/cannot-install-library-with-arduino-ide-2-0-3/1077981
- https://forum.arduino.cc/t/boards-and-libraries-fail-to-load-update/1052539
- https://forum.arduino.cc/t/newbie-unknown-proxy-host-blocking-the-install-of-libraries/1050777
- https://forum.arduino.cc/t/ide-2-0-4-on-win10-shows-no-ports-for-digispark-usb/1083255
- https://forum.arduino.cc/t/json-no-such-file/1119208/10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [ ] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-08-29 06:51
Thanks to the [recently added enhanced logging capabilities](https://github.com/arduino/arduino-ide/pull/1065) of Arduino IDE 2.x, I can now see that my use of `cc.arduino.cli.settings.v1.SettingsService.SetValue` in the previous demo was incorrect because Arduino IDE is instead using [the `cc.arduino.cli.settings.v1.SettingsService.Merge` method](https://arduino.github.io/arduino-cli/dev/rpc/settings/#mergerequest).

This is the relevant log output from trying to set "**No proxy**" in the Arduino IDE 2.0.0-rc9.2.snapshot-34a7fdb preferences:

```text
2022-08-28 22:31:32 daemon INFO 69 CALLED: /cc.arduino.cli.settings.v1.SettingsService/Merge
69 |  REQ:  {
69 |    "json_data": "{\n  \"board_manager\": {\n    \"additional_urls\": []\n  },\n  \"daemon\": {\n    \"port\": \"50051\"\n  },\n  \"directories\": {\n    \"data\": \"c:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\n    \"user\": \"c:\\\\Users\\\\per\\\\Documents\\\\Arduino\"\n  },\n  \"ide\": {\n    \"bundled\": false,\n    \"portable\": false\n  },\n  \"library\": {\n    \"enable_unsafe_install\": false\n  },\n  \"locale\": \"en\",\n  \"logging\": {\n    \"file\": \"\",\n    \"format\": \"text\",\n    \"level\": \"info\"\n  },\n  \"metrics\": {\n    \"addr\": \":9090\",\n    \"enabled\": true\n  },\n  \"network\": {},\n  \"output\": {\n    \"no_color\": false\n  },\n  \"sketch\": {\n    \"always_export_binaries\": false\n  },\n  \"updater\": {\n    \"enable_notification\": true\n  }\n}"
69 |  }
69 |  RESP: {}
69 CALL END
```

(note also the `\"network\": {}`)

## Setup

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: aa41d72e Date: 2022-08-29T05:36:08Z

$ arduino-cli config init
Config file written to: C:\Users\per\AppData\Local\Arduino15\arduino-cli.yaml

$ arduino-cli config set network.proxy foo  # set an arbitrary initial `network.proxy` configuration key value

$ arduino-cli daemon
Daemon is now listening on 127.0.0.1:50051
```

## Reproduce issue via the gRPC interface

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"foo\",\"user_agent_ext\":\"daemon\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🙂 The `network` key value is as expected.

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  -d '{"json_data": "{\"network\": {}}"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.Merge

{

}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"foo\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🐛 The `network` key was not set to `{}` according to [the `cc.arduino.cli.settings.v1.SettingsService.Merge` request](https://arduino.github.io/arduino-cli/dev/rpc/settings/#mergerequest) as expected.

😕 The `network.user_agent_ext` key is no longer present though.

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  -d '{"json_data": "{\"network\": {\"proxy\":\"bar\"}}"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.Merge

{

}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"bar\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🙂 The `network` key was set to `{"proxy": "bar"}` as expected.

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  -d '{"json_data": "{\"network\": {}}"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.Merge

{

}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/settings/v1/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.v1.SettingsService.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"foo\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🐛 The `network` key **reverted** to the previous `{"proxy": "foo"}`, rather than being set to `{}` according to the `cc.arduino.cli.settings.v1.SettingsService.Merge` request.

---

The odd thing is this was reported previously and then closed as fixed: https://github.com/arduino/arduino-cli/issues/1161

I notice it appears to be more of a "half fix" because it only addressed the bug in the `Merge` method, disregarding that the report was also about the `SetValue` method. But for the purposes of this problem with Arduino IDE 2.x, we only need to be concerned with the `Merge` method, since that is the only one in use.

This bug would give the impression there was a regression at some point after that fix. However, I have the same problems even using the Arduino CLI build from the very commit that made the fix. I also notice that the integration test assertion is not as I would expect:

https://github.com/arduino/arduino-cli/blob/fa478dd9636fe0b007bf6a49e78477053688f9a3/commands/daemon/settings_test.go#L65-L70

Why should the value of `daemon.port` be expected to be `"50051"` if the `daemon` key was just set to `{}`???

```text
$ git log -1 --oneline

fa478dd9 (HEAD) gpg: Signature made Tue Feb  2 08:41:13 2021 PST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
Fix gRPC interface function to merge configs (#1164)

$ arduino-cli daemon
```

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"foo\",\"user_agent_ext\":\"daemon\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🙂 The `network` key value is as expected.

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  -d '{"jsonData": "{\"network\": {}}"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.Merge

{

}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"foo\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🐛 The `network` key was not set to `{}` according to the `cc.arduino.cli.settings.Settings.Merge` request as expected.

😕 The `network.user_agent_ext` key is no longer present though...

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  -d '{"jsonData": "{\"network\": {\"proxy\":\"bar\"}}"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.Merge

{

}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"bar\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🙂 The `network` key was set to `{"proxy": "bar"}` as expected.

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  -d '{"jsonData": "{\"network\": {}}"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.Merge

{

}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto settings/settings.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.settings.Settings.GetAll

{
  "jsonData": "{\"board_manager\":{\"additional_urls\":[]},\"daemon\":{\"port\":\"50051\"},\"directories\":{\"data\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\",\"downloads\":\"C:\\\\Users\\\\per\\\\AppData\\\\Local\\\\Arduino15\\\\staging\",\"user\":\"C:\\\\Users\\\\per\\\\Documents\\\\Arduino\"},\"library\":{\"enable_unsafe_install\":false},\"logging\":{\"file\":\"\",\"format\":\"text\",\"level\":\"info\"},\"metrics\":{\"addr\":\":9090\",\"enabled\":true},\"network\":{\"proxy\":\"foo\"},\"output\":{\"no_color\":false},\"sketch\":{\"always_export_binaries\":false},\"updater\":{\"enable_notification\":true}}"
}
```

🐛 The `network` key **reverted** to the previous `{"proxy": "foo"}`, rather than being set to `{}` according to the `cc.arduino.cli.settings.Settings.Merge` request.

**Closed** 2023-06-27 14:53 UTC
Labels: topic: code, type: imperfection, topic: gRPC
