### ISSUE TITLE
"sketch new ." overwriting sketch without confirmation

### ISSUE THREAD

**Issue by xax** [arduino/arduino-cli#1175] opened 2021-02-06 17:32 UTC
### Current behavior

Running `arduino-cli sketch new .` (← note the dot) from a sketch directory overwrites an existing `.ino`sketch file without asking for confirmation, sketch folder (by accident or not) indeed not empty.

Consider for example the following situation (noted *bash*-like, though see system used below):
```bash
$ ls -R
.:
sketch_foo

./sketch_foo:
sketch_foo.ino
$
$ cd sketch_foo
$ arduino-cli sketch new .
$ # sketch_foo.ino will be overwritten with template boilerplate
```
### Expected behavior

The command should not be destructive like that by default. `ﬂetch new` should not overwrite anything; probably a flag forcing to overwrite may be useful.

### Environment

- CLI version (output of `arduino-cli version`):
  *arduino-cli alpha Version: 0.15.1 Commit: c7403ed2 Date: 2021-02-04T10:11:39Z*
- OS and platform:
  *Windows 10 [Version 10.0.19042.789], x64*

**Comment by ubidefeo** [comment] 2021-02-06 18:17
thank you for this one, @xax 

I think it's a regression we introduced recently because I can't remember having this issues (I always use the same sketch name when I test things around in my home folder).

@silvanocerza I have assigned this to you.
@rsora highest priority, please :)

**Closed** 2022-11-29 14:48 UTC
Labels: topic: code, type: imperfection
