### ISSUE TITLE
Upload baudrate

### ISSUE THREAD

**Issue by PeterWone** [arduino/arduino-cli#1015] opened 2020-10-08 07:10 UTC
There is currently no way to specify the baudrate when uploading via serial. This is a problem for devices with old bootloaders.

I suggest `--port-speed value` where value parses as a number eg 115200 or 57600

**Comment by per1234** [comment] 2020-10-08 07:14
Closing as duplicate of https://github.com/arduino/arduino-cli/issues/52

Please see that issue for the solution. There is no need to specify the baud rate because the board definition already specifies it. You only need to use the correct FQBN for your board.

**Closed** 2021-05-11 16:12 UTC
Labels: conclusion: duplicate
