### ISSUE TITLE
Waiting too long for upload port on Win10 x64

### ISSUE THREAD

**Issue by cccczl** [arduino/arduino-cli#1270] opened 2021-04-19 13:20 UTC
### Environment

- CLI version (output of `arduino-cli version`): arduino-cli.exe alpha Version: 0.18.1 Commit: b3cf8e19 Date: 2021-04-13T13:08:30Z
- OS and platform: windows 10 20H2 x64

### Additional context

```text
PS C:\soft\arduinocli> .\arduino-cli.exe upload -pCOM22 --fqbn arduino:avr:leonardo --log-level debug --verbose cli-blink
Performing 1200-bps touch reset on serial port COM22
Waiting for upload port...
"D:\s\aopu\openblock-link\tools\Arduino\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude" "-CD:\s\aopu\openblock-link\tools\Arduino\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf" -v -V -patmega32u4 -cavr109 "-PCOM22" -b57600 -D "-Uflash:w:C:\Users\cccczl\AppData\Local\Temp\arduino-sketch-3ED8B0558B8AF24D78023D1FFBA89886/cli-blink.ino.hex:i"

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "D:\s\aopu\openblock-link\tools\Arduino\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

         Using Port                    : COM22
         Using Programmer              : avr109
         Overriding Baud Rate          : 57600
         AVR Part                      : ATmega32U4
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  9000  9000 0x00 0x00
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : butterfly
         Description     : Atmel AppNote AVR109 Boot Loader

Connecting to programmer: .avrdude: butterfly_recv(): programmer is not responding
```

**Comment by per1234** [comment] 2022-03-31 06:02
Thanks for your report @cccczl. I'm going to close this as most likely not caused by a problem in Arduino CLI. It is more likely something like the sketch program breaking the 1200 baud touch detection, a missing bootloader, etc.

If anyone has additional evidence to indicate this error is caused by a problem in the Arduino CLI code base, please comment here and I'll investigate.

**Closed by per1234** 2022-03-31 06:02 UTC
