### ISSUE TITLE
anic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shellus** [arduino/arduino-cli#93] opened 2018-11-27 07:36 UTC
```
C:\Users\shellus\Documents\Arduino\MyFirstSketch>arduino-cli core update-index
 0 / ? [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------=]   0.00%p
anic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4012cc]

goroutine 6 [running]:
sync/atomic.AddUint64(0x11e6c074, 0x1000, 0x0, 0x1000, 0x1000)
        /home/jenkins/go1.10.2-patched/src/sync/atomic/asm_386.s:112 +0xc
github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).AsyncRun(0x11e6c060)
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:82 +0x162
created by github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).RunAndPoll
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:61 +0x84

C:\Users\shellus\Documents\Arduino\MyFirstSketch>

```

I just do this:
1: Download `https://downloads.arduino.cc/arduino-cli/arduino-cli-0.3.2-alpha.preview-windows.zip`
2: `arduino-cli sketch new MyFirstSketch`
3: `cd C:\Users\shellus\Documents\Arduino\MyFirstSketch`
4: `arduino-cli core update-index`

I am using the latest windows10

**Comment by per1234** [comment] 2018-11-27 07:54
Closing as duplicate of https://github.com/arduino/arduino-cli/issues/87

The bug has been fixed but that was done after the 0.3.2-alpha release.

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/arduino-cli/issues?&q=
If you do find the issue has already been reported or a fix has been submitted, you are welcome to give it a "thumbs up" by clicking on the smiley face icon at the top right to show your support. Please only comment on the issue if you have additional information to add.

**Closed by per1234** 2018-11-27 07:54 UTC
