### ISSUE TITLE
How can I add compilation parameters when I execute arduino-cli compile?

### ISSUE THREAD

**Issue by Dortmund-Reus** [arduino/arduino-cli#1572] opened 2021-11-26 03:53 UTC
When using gcc, I can use -D option to add compilation parameters, but how can I do that when using arduino-cli?

**Comment by per1234** [comment] 2021-11-26 04:20
Duplicate of https://github.com/arduino/arduino-cli/issues/210

If you would like assistance using Arduino CLI, feel free to ask on the Arduino Forum:
https://forum.arduino.cc/c/software/arduino-cli/89

**Closed by per1234** 2021-11-26 04:20 UTC
