### ISSUE TITLE
Install chipkit- cores in win 11

### ISSUE THREAD

**Issue by mogjen** [arduino/arduino-cli#2430] opened 2023-11-16 11:34 UTC
This is the problem in win 11.

```text
Error: 13 INTERNAL: Cannot install tool chipKIT:pic32-tools@1.43-pic32gcc: searching package root dir: no unique root dir in archive, found 'C:\Users\motoj\AppData\Local\Arduino15\tmp\package-200568146\bin' and 'C:\Users\motoj\AppData\Local\Arduino15\tmp\package-200568146\lib'
```

In win 10 is it like this.

In win 11 I do not have the `AppData` subfolder under my username folder. There is a subfolder named `.arduinoIDE/`.

where do I have  to put chipkit-cores

**Comment by per1234** [comment] 2023-11-16 19:53
Hi @mogjen. Thanks for your interest in this free open source project.

> ```text
> Error: 13 INTERNAL: Cannot install tool chipKIT:pic32-tools@1.43-pic32gcc: searching package root dir: no unique root dir in archive, found 'C:\Users\motoj\AppData\Local\Arduino15\tmp\package-200568146\bin' and 'C:\Users\motoj\AppData\Local\Arduino15\tmp\package-200568146\lib'
> ```

This is a duplicate of https://github.com/arduino/arduino-cli/issues/325 (which was previously duplicated specific to the `chipKIT:pic32` platform at https://github.com/arduino/arduino-cli/issues/2131).

> where do I have to put chipkit-cores

Arduino's issue trackers are only to be used to report bugs or feature requests specific to the project. Support requests must be submitted on the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Closed by per1234** 2023-11-16 19:53 UTC
Labels: topic: code, type: imperfection
